return {
    std = "lua54",
    globals = {
        "Config",
        "GetPlayerJob",
        "RegisterFrameworkEvents",
        "IsPlayerInAllowedVehicle",
        "IsPlayerInAllowedJob",
        "CanUseCarMegaphone",
        "ShowNotification",
        "ActivateMegaphone",
        "DeactivateMegaphone",
        "ActivateVisualEffects",
        "DeactivateVisualEffects",
        "ApplyMegaphoneSubmix",
        "RemoveMegaphoneSubmix",
        "LogMegaphoneUsage",
    },

    read_globals = {
        "Citizen",
        "CreateThread",
        "Wait",
        "SetTimeout",
        "GetResourceState",
        "GetCurrentResourceName",
        "LoadResourceFile",
        "SaveResourceFile",
        "IsDuplicityVersion",
        "RegisterCommand",
        "RegisterNetEvent",
        "AddEventHandler",
        "RemoveEventHandler",
        "TriggerEvent",
        "TriggerServerEvent",
        "TriggerClientEvent",
        "RegisterKeyMapping",
        "PlayerPedId",
        "GetPlayerPed",
        "PlayerId",
        "GetPlayerName",
        "GetPlayerIdentifiers",
        "source",
        "GetEntityCoords",
        "GetEntityHeading",
        "GetEntityModel",
        "NetworkGetNetworkIdFromEntity",
        "IsPedInAnyVehicle",
        "GetPedInVehicleSeat",
        "GetVehiclePedIsIn",
        "GetVehicleClass",
        "GetDisplayNameFromVehicleModel",
        "SetVehicleLights",
        "SetVehicleIndicatorLights",
        "SetNotificationTextEntry",
        "AddTextComponentString",
        "DrawNotification",
        "PlaySoundFrontend",
        "CreateAudioSubmix",
        "SetAudioSubmixEffectRadioFx",
        "SetAudioSubmixEffectParamInt",
        "SetAudioSubmixEffectParamFloat",
        "AddAudioSubmixOutput",
        "MumbleSetAudioInputIntent",
        "MumbleSetSubmixForServerId",
        "MumbleSetAudioInputDistance",
        "MumbleSetTalkerProximity",
        "exports",
        "ESX",
        "QBCore",
        "lib",
        "MySQL",
        "fx_version",
        "game",
        "lua54",
        "author",
        "description",
        "version",
        "dependency",
        "shared_scripts",
        "client_scripts",
        "server_scripts",
    },

    ignore = {
        "211/_.*",
        "212",
        "213",
        "311",
        "542",
    },

    exclude_files = {
        "**/node_modules/**",
        "**/.git/**",
        "**/build/**",
        "**/dist/**",
        "**/.vscode/**",
    },

    max_line_length = 130,

    files = {
        ["config/*.lua"] = {
            globals = { "Config" },
            max_line_length = false,
        },

        ["fxmanifest.lua"] = {
            globals = {
                "fx_version",
                "game",
                "lua54",
                "author",
                "description",
                "version",
                "dependency",
                "shared_scripts",
                "client_scripts",
                "server_scripts",
            },
        },

        ["bridge/framework.lua"] = {
            globals = {
                "Config",
                "GetPlayerJob",
                "RegisterFrameworkEvents",
                "IsPlayerInAllowedVehicle",
                "IsPlayerInAllowedJob",
                "CanUseCarMegaphone",
                "ShowNotification",
            },
        },

        ["client/main.lua"] = {
            globals = {
                "ActivateMegaphone",
                "DeactivateMegaphone",
                "ActivateVisualEffects",
                "DeactivateVisualEffects",
            },
            ignore = { "211" },
        },

        ["client/submix.lua"] = {
            globals = {
                "ApplyMegaphoneSubmix",
                "RemoveMegaphoneSubmix",
            },
            max_line_length = 140,
        },

        ["logs/logs.lua"] = {
            globals = {
                "LogMegaphoneUsage",
            },
        },
    },
}
